# Because of the nature of this repo, you will need a PAT for your other repo
# in order to update and sync the files from the workflow.
#
# Needs: contents(write), workflows(write), actions(write)
#
# This token should be stored as a WORKFLOW_UPDATE secret

name: Auto Merge Upstream
on:
  workflow_dispatch:
  # I don't know why, but it appears that this cron is never running
  # And it's completely mysterious.
  schedule:
    - cron: '12,21,33,42,58 * * * *'

defaults:
  run:
    shell: bash

permissions:
  actions: write

jobs:
  clean_base:
    name: Actions Clean
    uses: ./.github/workflows/clean_actions.yml

  sync:
    name: Sync All Other Forks
    if: ${{ github.repository != 'socksthewolf/workflows' }}
    runs-on: ubuntu-latest
    steps:
      - name: Fail if secrets are not defined
        env:
          has_token: ${{ secrets.WORKFLOW_UPDATE }}
        if: ${{ env.has_token == '' }}
        run: echo "This needs a PAT to continue, please set one with the correct permissions!" && exit 1
      - name: Run GH Sync
        # main is hardcoded here because cron scripts cannot run on any
        # branch besides the default one (which is main across all projects)
        run: "gh api --method POST -H 'Accept: application/vnd.github+json' -H 'X-GitHub-Api-Version: 2026-03-10' /repos/$REPO/merge-upstream -f 'branch=main'"
        env:
          REPO: ${{ github.repository }}
          GH_TOKEN: ${{ secrets.WORKFLOW_UPDATE }}

