# Because of the nature of this repo, you will need a PAT for your other repo
# in order to update and sync the files from the workflow.
#
# Needs: contents(write), workflows(write), actions(write)
#
# This token should be stored as a WORKFLOW_UPDATE secret
name: Auto Merge From Upstream
on:
  workflow_dispatch: {}
  workflow_call:
    secrets:
      WORKFLOW_UPDATE:
        description: "This must be a Personal Access Token with the needs defined in this file"
        required: true
    outputs:
      sync_result:
        value: ${{ jobs.sync.outputs.sync_result }}
        description: "The result of the sync operation"
      merge_type:
        value: ${{ jobs.sync.outputs.merge_type }}
        description: "Merge operation that was performed"
      success:
        value: ${{ jobs.sync.result == 'success'}}
        description: "If the sync operation completed successfully"

  # I don't know why, but it appears that this cron is never running
  # And it's completely mysterious.
  schedule:
    - cron: '12,21,33,42,58 * * * *'

permissions:
  actions: write

defaults:
  run:
    shell: bash

concurrency:
  group: "autosync"
  cancel-in-progress: true

jobs:
  clean_actions:
    uses: ./.github/workflows/clean_actions.yml

  sync:
    name: Sync Fork
    if: ${{ github.repository != 'socksthewolf/workflows' }}
    outputs:
      sync_result: ${{ steps.gh-sync.outputs.result }}
      merge_type: ${{ steps.gh-sync.outputs.merge_type }}
    runs-on: ubuntu-latest
    steps:
      - name: Fail if secrets are not defined
        env:
          has_token: ${{ secrets.WORKFLOW_UPDATE }}
        if: ${{ env.has_token == '' }}
        run: echo "This needs a PAT to continue, please set one with the correct permissions!" && exit 1
      - name: Run GH Sync
        id: gh-sync
        # main is hardcoded here because cron scripts cannot run on any
        # branch besides the default one (which is main across all projects)
        run: |
          response=$(gh api --method POST -H 'Accept: application/vnd.github+json' -H "X-GitHub-Api-Version: $API_VERSION" /repos/$REPO/merge-upstream -f 'branch=main')
          ret_code=$?
          readonly response
          readonly ret_code
          message=$(echo $response | jq -r .message) >> "$GITHUB_OUTPUT"
          merge_type=$(echo $response | jq -r .merge_type) >> "$GITHUB_OUTPUT"
          echo "Result: $message"
          echo "Used Merge: $merge_type"
          echo "Exiting with code $ret_code"
          exit $ret_code
        env:
          # Swaps
          REPO: ${{ github.repository }}
          API_VERSION: "2026-03-10"
          # GH CLI uses the value in GH_TOKEN to do operations
          GH_TOKEN: ${{ secrets.WORKFLOW_UPDATE }}
