name: Auto Push Wrangler Updates
on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

concurrency:
  group: wrangler
  cancel-in-progress: false
  queue: single

permissions:
  actions: write

jobs:
  clean_actions:
    uses: ./.github/workflows/clean_actions.yml

  get-repos:
    name: Get All Repos
    runs-on: ubuntu-latest
    environment: wrangler-update
    outputs:
      repos: ${{ steps.get-repos.outputs.repos }}
    steps:
      - name: Query Repositories
        id: get-repos
        uses: raven-actions/get-repos@main
        with:
          owner: ${{ github.repository_owner }}
          github-token: ${{ secrets.READ_REPO_TOKEN }}
          topics: "wrangler,cloudflare"
          operator: "OR"

  sync-repos:
    name: Dispatch Event (${{ matrix.repo.name }})
    if: ${{ needs.get-repos.outputs.repos != '[]' }} # make sure repos exist
    runs-on: ubuntu-latest
    environment: wrangler-update
    needs:
      - get-repos
    strategy:
      matrix:
        repo: ${{ fromJson(needs.get-repos.outputs.repos) }}
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          token: ${{ secrets.READ_REPO_TOKEN }}
          repository: ${{ matrix.repo.full_name }}

      - name: Find Node Directory
        id: node_directory
        run: |
          dir=$(dirname $(realpath $(find . -name 'wrangler.toml')))
          echo "dir=${dir/$WORKSPACE/}" >> "$GITHUB_OUTPUT"
          echo ${dir/$WORKSPACE/}
          echo "ver=${dir/$WORKSPACE/}/.node-version" >> "$GITHUB_OUTPUT"
          echo "lock=${dir/$WORKSPACE/}/package-lock.json" >> "$GITHUB_OUTPUT"
          echo "pack=${dir/$WORKSPACE/}/package.json" >> "$GITHUB_OUTPUT"
          echo ${dir/$WORKSPACE/}/package-lock.json
        env:
          WORKSPACE: ${{ github.workspace }}

      - name: Install Node
        id: node
        uses: actions/setup-node@v7
        with:
          cache: "npm"
          cache-dependency-path: "*package-lock.json"
          node-version-file: ${{ steps.node_directory.outputs.ver }}
          package-manager-cache: true

      - name: Update
        if: success()
        run: |
          if [[ "$NODE_DIR" != "" ]]; then
            cd $NODE_DIR
          fi
          "npm install wrangler@latest --save-dev"
        env:
          NODE_DIR: ${{ steps.node_directory.outputs.dir }}

      - name: Read packages.json
        id: package_read
        uses: socksthewolf/github-action-json@v1.0.3
        with:
          path: ${{ steps.node_directory.outputs.pack }}

      - name: Check for types
        id: type_check
        if: ${{ steps.package_read.outputs.scripts }}
        run: |
          check_field=$(echo "$JSON_DATA" | jq -r .types)
          if [[ "$check_field" != null ]]; then
            echo "has_data=true" >> "$GITHUB_OUTPUT"
          else
            echo "has_data=false" >> "$GITHUB_OUTPUT"
          fi
        env:
          JSON_DATA: ${{ steps.package_read.outputs.scripts }}

      - name: Build types
        if: ${{ success() && steps.type_check.outputs.has_data == 'true' }}
        run: |
          if [[ "$NODE_DIR" != "" ]]; then
            cd $NODE_DIR
          fi
          "npm run types"
        env:
          NODE_DIR: ${{ steps.node_directory.outputs.dir }}

        # Set up the GPG Key for Signing Commits
      - name: Setup GPG Key
        id: import-gpg
        uses: crazy-max/ghaction-import-gpg@2dc316deee8e90f13e1a351ab510b4d5bc0c82cd
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true

        # May consider auto committing the update tbh
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1
        id: commit
        with:
          token: ${{ secrets.CREATE_PR_TOKEN }}
          delete-branch: true
          commit-message: "Update Wrangler"
          title: "Chore: Wrangler Update"
          assignees: ${{ github.repository_owner }}
          committer: "${{ steps.import-gpg.outputs.name }} <${{ steps.import-gpg.outputs.email }}>"
          body: "As promised, the update to your wrangler dependencies"
          branch: "chore/wrangler-update"
