# Builds, cleans, optimizes and publishes a Jekyll Website onto Cloudflare
#
# This requires:
#
# * A filter_rules.yml in .github/
#   * This file must have a rule in it for "clear_cache"
# * A run.sh in .github/
#   * But only if needs_after_run is true
# * A Github environment named "jekyll" or repo variables that defines:
#   * secrets:PERSONAL_TOKEN
#   * secrets:CLOUDFLARE_TOKEN
#   * vars:CLOUDFLARE_ACCOUNT_ID
#
#   Both secrets can also be manually passed.
#
# * package.json that has:
#   * wrangler
#   * run script called "purge-ci" (this doesn't actually have to do anything)

name: Build & Deploy Jekyll
on:
  workflow_call:
    inputs:
      ref:
        description: "Pass github.ref"
        type: string
        required: true
      force_clear:
        description: "If we should force clear the cache"
        type: boolean
        default: false
      should_clean:
        description: "If we should clean actions & deploys before execution"
        type: boolean
        default: false
      ruby_cache_version:
        description: "The Ruby cache storage number"
        type: number
        default: 1
      remove_feeds:
        description: "If jekyll feeds should be removed automatically"
        type: boolean
        default: true
      needs_after_run:
        description: "If we should execute a shell script after running the build"
        type: boolean
        default: false
    secrets:
      PERSONAL_TOKEN:
        description: "Passed to the shell via a $TOKEN flag if needs_after_run is true"
      CLOUDFLARE_TOKEN:
        description: "This API Token must be able to clear cache and deploy sites/bindings"
    outputs:
      built:
        value: ${{ jobs.build.outputs.built == true }}
        description: "If the Jekyll site was successfully built"
      deployed:
        value: ${{ jobs.build.outputs.deployed == true }}
        description: "If the site was able to be deployed to Cloudflare"

permissions:
  contents: read
  actions: write
  deployments: write

defaults:
  run:
    shell: bash

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "jekyll_build"
  cancel-in-progress: false
  queue: single

jobs:
  clean_actions:
    if: ${{ inputs.should_clean == true }}
    uses: ./.github/workflows/clean_actions.yml

  clean_deploys:
    if: ${{ inputs.should_clean == true }}
    uses: ./.github/workflows/clean_deploys.yml
    with:
      environment: jekyll

  build:
    runs-on: ubuntu-latest
    name: Jekyll Build
    environment: jekyll
    outputs:
      clear_cache: ${{ steps.filter.outputs.clear_cache == true }}
      built: ${{ steps.build.conclusion == 'success' }}
      deployed: ${{ steps.wrangler-deploy.conclusion == 'success' }}
    steps:
        # Check out the repo files
      - name: Checkout
        uses: actions/checkout@v7

        # Check for if we should Clear the Cache at the end of all steps
      - name: Cache Clear Check
        uses: dorny/paths-filter@7b450fff21473bca461d4b92ce414b9d0420d706
        id: filter
        with:
          base: ${{ inputs.ref }}
          filters: ".github/filter_rules.yml"

        # Needed for PurgeCSS/Wrangler
      - name: Setup node
        uses: actions/setup-node@v7
        with:
          cache: "npm"
          node-version-file: ".node-version"
          package-manager-cache: true
      - name: Node Package Install
        if: success()
        id: node
        run: npm install

        # Also set up Ruby to build for Jekyll
      - name: Setup Ruby
        uses: ruby/setup-ruby@a30dfa457ad68707b8b910ac3a244714b61c0626
        with:
          bundler-cache: true
          cache-version: ${{ inputs.ruby_cache_version }}
      - name: Build with Jekyll
        if: success()
        id: build
        # Outputs to the './_site' directory by default
        # Please do not change that directory via your configs
        run: bundle exec jekyll build --baseurl ""
        env:
          JEKYLL_ENV: production

        # Run arbitrary shell for running commands after build
      - name: After Build Execution
        if: ${{ success() && inputs.needs_after_run == true }}
        env:
          TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        run: bash .github/run.sh

        # Minimize/Purge any excess CSS rules that are unused
      - name: Purge CSS
        # idk why but the output directory is much different than what it is on windows
        # this should fix all of it though
        if: ${{ success() && steps.node.conclusion == 'success' }}
        run: npm run purge-ci

        # Remove excess files
      - name: No Source Maps
        run: rm -rf _site/assets/**/*.map
      - name: Remove All Feeds
        if: ${{ inputs.remove_feeds == true }}
        run: rm -f _site/feed.xml

        # Convert jekyll redirects into CF redirects
      - name: Redirect Update
        uses: socksthewolf/jekyll-cloudflare-redirects@0ca292af046fe1f9b482bed5adb3964c78cf31c3

        # Take everything in our runtime and punt it to Cloudflare
        # Upload directory to CF
      - name: Upload to Cloudflare
        if: ${{ success() && steps.node.conclusion == 'success' }}
        id: wrangler-deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ vars.CLOUDFLARE_ACCOUNT_ID }}
        run: npm run deploy

  # Delete the cloudflare cache after deploy
  clear:
    needs: build
    if: ${{ needs.build.outputs.deployed == true && (needs.build.outputs.clear_cache == true || inputs.force_clear == true) }}
    name: Cloudflare Cache Cleaner
    uses: ./.github/workflows/clear_cache.yml
    secrets:
      CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}