# Build, uploads and publishes OpenAPI specs.
#
# Must have a openapi environment.
# This environment must have:
#   var:CLOUDFLARE_ZONE
#   secret:CLOUDFLARE_TOKEN
#
# You can also bypass the environment by passing CLOUDFLARE_TOKEN explicitly

name: Build OpenAPI Spec
on:
  workflow_call:
    inputs:
      ref:
        description: "Pass github.ref"
        type: string
        required: true
      needs_node:
        description: "If the OpenAPI spec requires node to build the spec"
        type: boolean
        default: false
      is_download:
        description: "If the spec should be downloaded from an URL"
        type: boolean
        default: false
      download_uri:
        description: "If the spec is a download, where can the download be found"
        type: string
        default: ""
      clean_deploys:
        description: "If we should clear all previous deployments of this action"
        type: boolean
        default: false
    secrets:
      CLOUDFLARE_TOKEN:
        description: "A Cloudflare API Token with Domain API Gateway Edit Support"

defaults:
  run:
    shell: bash

permissions:
  contents: read
  actions: write
  deployments: write

jobs:
  clean_deploys:
    name: Cleanup Previous Deployments
    if: ${{ inputs.clean_deploys }}
    uses: ./.github/workflows/clean_deploys.yml
    with:
      environment: openapi

  build_spec:
    name: Generate & Upload Spec
    runs-on: ubuntu-latest
    environment: openapi
    steps:
        # Check if we can run
      - name: Error if CF token is missing
        id: token
        env:
          token_check: ${{ secrets.CLOUDFLARE_TOKEN }}
        if: ${{ env.token_check == '' }}
        run: echo "Missing Cloudflare Token! Exiting..." && exit 1

        # Checkout all files
      - name: Checkout Repository
        if: ${{ inputs.is_download != 'true' }}
        uses: actions/checkout@v7

        # Build sitemap with node
      - name: Setup Node
        if: ${{ inputs.needs_node }}
        uses: actions/setup-node@v7
        with:
          cache: "npm"
          node-version-file: ".node-version"
          package-manager-cache: true

      - name: Install and Build Spec
        if: ${{ inputs.needs_node }}
        run: npm install && npm run openapi

        # Download Existing OpenAPI spec if provided
      - name: Fail if download but no Download URI
        if: ${{ inputs.is_download && inputs.download_uri == '' }}
        run: exit 1
      - name: Download OpenAPI Spec
        if: ${{ inputs.is_download && inputs.download_uri != '' }}
        run: curl --no-progress-meter --output openapi.json "$DOWNLOAD_URL"
        env:
          DOWNLOAD_URL: ${{ inputs.download_uri }}

        # Check to see that we have the openapi file at all
      - name: Check for Spec Existing
        id: spec_check
        run: |
          if test -f "openapi.json"; then
            echo "has_file=true" >> $GITHUB_OUTPUT
            echo "File Exists"
          else
            echo "has_file=false" >> $GITHUB_OUTPUT
            echo "File Missing!"
          fi

        # If we have the file, upload it to CF API Shield
      - name: Upload Spec to API Shield
        if: ${{ steps.spec_check.outputs.has_file == 'true' }}
        uses: socksthewolf/cloudflare-upload-spec@4aa5efd32ce6fc898dcb794ccd7e3001568cce10
        with:
          zone_id: ${{ vars.CLOUDFLARE_ZONE }}
          api_token: ${{ secrets.CLOUDFLARE_TOKEN }}
          delete_others: true

        # Additionally, save it to our GH artifacts
      - name: Upload Spec as Artifact
        if: ${{ success() && steps.spec_check.outputs.has_file == 'true' }}
        uses: actions/upload-artifact@v7
        with:
          name: openapi-spec-${{ inputs.ref }}
          path: ./openapi.json
          archive: false
          if-no-files-found: error
