# This workflow requires an environment named Cloudflare or repo settings
# with the following:
#   vars:CLOUDFLARE_ZONE
#   vars:CLOUDFLARE_ACCOUNT_ID
#   secret:CLOUDFLARE_TOKEN
name: Clear Cloudflare Cache

on:
  workflow_call:
    secrets:
      CLOUDFLARE_TOKEN:
    inputs:
      paths:
        type: string
        description: "If there are specific URLS to be cleared, this should be a multi-line input. If zone should be cleared, leave blank"
        default: ""

jobs:
  clear_cache:
    name: Clear Cloudflare Cache
    runs-on: ubuntu-latest
    permissions: {}
    environment: cloudflare
    steps:
      - name: Clearing Entire Zone
        if: ${{ inputs.paths == '' }}
        run: echo true
      - name: Clearing Individual Paths
        if: ${{ inputs.paths != '' }}
        run: echo true
      - name: Write CF Cache Changes
        uses: Cyb3r-Jak3/action-cloudflare-cache@6ebf798ade84e7ab7da249404e0c3b9aecf54f88
        with:
          zone: ${{ vars.CLOUDFLARE_ZONE }}
          api_token: ${{ secrets.CLOUDFLARE_TOKEN }}
          account_id: ${{ vars.CLOUDFLARE_ACCOUNT_ID }}
          URLs: ${{ inputs.paths }}