name: Clean GH Deploys
on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true

permissions:
  deployments: write

jobs:
  # Clean up github job
  clean_deploys:
    name: Cleanup Previous Deployments
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: strumwolf/delete-deployment-environment@035f6d27c8b8951729f4d71b2d3d6a7975139476
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: ${{ inputs.environment }}
          onlyRemoveDeployments: true