# ScamGuard uses this to deploy its python workers.
#
# This requires an environment called "production"
# as well as ./github/filters.yml in the repo
#
# This filter should define:
# * core_updated <-- which python files should trigger a restart

name: Deploy Bots To Cloud via SSH
on:
  workflow_call:
    secrets:
      SSH_HOST:
      SSH_PRIVATE_KEY:
      SSH_USER:
    inputs:
      ref:
        type: string
        required: true
      path:
        type: string
        required: true
      force_restart:
        type: boolean
        default: false

permissions:
  deployments: write
  contents: read

jobs:
  cleanup:
    name: Cleanup Previous Deployments
    uses: ./.github/workflows/clean_deploys.yml
    with:
      environment: production

  deploy:
    name: Deploy Bot
    environment: production
    runs-on: ubuntu-latest
    steps:
    - name: Checkout files
      uses: actions/checkout@v7
      with:
        ref: ${{ inputs.ref }}

    - name: Core Program Restart Check
      uses: dorny/paths-filter@7b450fff21473bca461d4b92ce414b9d0420d706
      id: filter
      with:
        base: ${{ inputs.ref }}
        filters: .github/filters.yml

    - name: Dependencies Update Check
      uses: dorny/paths-filter@7b450fff21473bca461d4b92ce414b9d0420d706
      id: check_deps
      with:
        base: ${{ inputs.ref }}
        filters: |
          update_needed:
            - 'requirements.txt'
            - '.runtime/update.sh'

    - name: Configure SSH
      run: |
        mkdir -p ~/.ssh/
        echo "$SSH_KEY" > ~/.ssh/staging.key
        chmod 600 ~/.ssh/staging.key
        cat >>~/.ssh/config <<END
        Host staging
          HostName $SSH_HOST
          User $SSH_USER
          IdentityFile ~/.ssh/staging.key
          StrictHostKeyChecking no
        END
      env:
        SSH_HOST: ${{ secrets.SSH_HOST }}
        SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SSH_USER: ${{ secrets.SSH_USERNAME }}

      # If any runtime files updated, then we need to stop all bot instances.
    - name: Kill Running Instances
      id: kill_bot
      continue-on-error: true
      if: steps.check_deps.outputs.update_needed == 'true' || steps.filter.outputs.core_updated == 'true' || inputs.force_restart == 'true'
      run: ssh staging $EXEC_STR
      env:
        EXEC_STR: "cd ${{ inputs.path }} && .runtime/kill.sh"

    # We want to update the project regardless.
    - name: Remote Sync Project
      run: ssh staging $EXEC_STR
      env:
        EXEC_STR: "cd ${{ inputs.path }} && .runtime/pull.sh"

    # attempt to update any python dependencies
    - name: Update Python Dependencies
      id: deps_update
      if: steps.check_deps.outputs.update_needed == 'true'
      continue-on-error: false
      run: ssh staging $EXEC_STR
      env:
        EXEC_STR: "set -e && cd ${{ inputs.path }} && .runtime/update.sh"

    # restart instances
    - name: Restart Instances
      if: ${{ always() && (steps.deps_update.conclusion == 'success' || steps.deps_update.outcome == 'skipped') && steps.kill_bot.conclusion == 'success' }}
      run: ssh staging $EXEC_STR
      env:
        EXEC_STR: "cd ${{ inputs.path }} && .runtime/run.sh -d"

    # Remove the key once done
    - name: Kill SSH Key Add
      if: ${{ always() }}
      run: rm -f ~/.ssh/staging.key