# Build, uploads and publishes OpenAPI specs.
#
# Must have a openapi environment.
# This environment must have:
#   var:CLOUDFLARE_ZONE
#   secret:CLOUDFLARE_TOKEN
#
# You can also bypass the environment by passing CLOUDFLARE_TOKEN explicitly

name: Build OpenAPI Spec
on:
  workflow_call:
    inputs:
      ref:
        type: string
        required: true
      needs_node:
        type: boolean
      is_download:
        type: boolean
      download_uri:
        type: string
      clean_deploys:
        type: boolean
    secrets:
      CLOUDFLARE_TOKEN:

defaults:
  run:
    shell: bash

permissions:
  contents: read
  actions: write
  deployments: write

jobs:
  clean_deploys:
    runs-on: ubuntu-latest
    continue-on-error: true
    if: ${{ inputs.clean_deploys }}
    name: Clean Old OpenAPI Deploys
    steps:
      - uses: strumwolf/delete-deployment-environment@035f6d27c8b8951729f4d71b2d3d6a7975139476
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: openapi
          onlyRemoveDeployments: true

  build_spec:
    name: Generate & Upload Spec
    runs-on: ubuntu-latest
    environment: openapi
    steps:
      - name: Error if CF token is missing
        id: token
        env:
          token_check: ${{ secrets.CLOUDFLARE_TOKEN }}
        if: ${{ env.token_check == '' }}
        run: echo "Missing Cloudflare Token! Exiting..." && exit 1
      - name: Checkout
        uses: actions/checkout@v7.0.0
      - name: Setup Node
        if: ${{ inputs.needs_node }}
        uses: actions/setup-node@v6
        with:
          cache: "npm"
          node-version-file: ".node-version"
          package-manager-cache: true
      - name: Node Install Packages
        if: ${{ inputs.needs_node }}
        run: npm install
      - name: Run OpenAPI Gen
        if: ${{ inputs.needs_node }}
        run: npm run openapi
      - name: Download OpenAPI Spec
        if: ${{ inputs.is_download && inputs.download_uri != '' }}
        run: curl --no-progress-meter --output openapi.json "$DOWNLOAD_URL"
        env:
          DOWNLOAD_URL: ${{ inputs.download_uri }}
      - name: Check for Spec Existing
        id: spec_check
        run: |
          if test -f "openapi.json"; then
            echo "has_file=true" >> $GITHUB_OUTPUT
            echo "File Exists"
          else
            echo "has_file=false" >> $GITHUB_OUTPUT
            echo "File Missing!"
          fi
      - name: Upload Spec to API Shield
        if: ${{ steps.spec_check.outputs.has_file == 'true' }}
        uses: socksthewolf/cloudflare-upload-spec@4aa5efd32ce6fc898dcb794ccd7e3001568cce10
        with:
          zone_id: ${{ vars.CLOUDFLARE_ZONE }}
          api_token: ${{ secrets.CLOUDFLARE_TOKEN }}
          delete_others: true
      - name: Upload Spec as Artifact
        if: ${{ success() && steps.spec_check.outputs.has_file == 'true' }}
        uses: actions/upload-artifact@v7
        with:
          name: openapi-spec-${{ inputs.ref }}
          path: ./openapi.json
          archive: false
          if-no-files-found: error
