# Dependabot loves to constantly fail on this one
# Plus, we usually have to update types
#
# So this task handles it by opening a PR
#
# Requires that GH Actions can open PRs.
# Could probably be solved with an app integration
name: Update Wrangler Task
on:
  workflow_call:
    inputs:
      npm_directory:
        description: "The working directory for npm"
        type: string
        default: "./"
      update_types:
        description: "If the types file needs to be updated too"
        type: boolean
        default: false
      assignees:
        description: "The default assigness to the PR"
        type: string
        default: ${{ github.repository_owner }}
    outputs:
      success:
        value: ${{ jobs.update_wrangler.outputs.committed }}
        description: "If a commit was made"
      sha:
        value: ${{ jobs.update_wrangler.outputs.sha }}
        description: "The sha value of the commit"

permissions:
  contents: write
  pull-requests: write

defaults:
  run:
    shell: bash

concurrency:
  group: wrangler
  cancel-in-progress: false

jobs:
  update_wrangler:
    outputs:
      committed: ${{ steps.commit.outputs.pull-request-operation == 'created' || steps.commit.outputs.pull-request-operation == 'updated' }}
      sha: ${{ steps.commit.outputs.pull-request-head-sha }}
    runs-on: "ubuntu-latest"
    name: Update Wrangler
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Update Working directory
        if: ${{ inputs.npm_directory != './' }}
        run: cd $DIRECTORY
        env:
          DIRECTORY: ${{ inputs.npm_directory }}

      - name: Install Node
        id: node
        uses: actions/setup-node@v7
        with:
          cache: "npm"
          node-version-file: ".node-version"
          package-manager-cache: true

      - name: Update
        if: success()
        run: "npm install wrangler@latest --save-dev"

      - name: Update types
        if: ${{ success() && inputs.update_types == true }}
        run: "npm run types"

      - name: Change Back Path
        if: ${{ inputs.npm_directory != './' }}
        run: cd ..

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v8
        id: commit
        with:
          sign-commits: true
          delete-branch: true
          commit-message: "Update Wrangler"
          title: "Chore: Wrangler Update"
          assignees: ${{ inputs.assignees }}
          body: "As promised, the update to your wrangler dependencies"
          branch: "chore/wrangler-update"
          branch-suffix: timestamp